name: 'Release Draft'

on:
  push:
    branches:
      - test

permissions:
  actions: write
  contents: write
  deployments: write
  packages: write
  pull-requests: write
  repository-projects: write

jobs:
  ubuntu-latest-aurora-release-gh-draft:
    name: 'Build And Release Draft'
    runs-on: ubuntu-latest
    steps:
      - name: 'Clone Repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Build Driver'
        run: |
          ./gradlew --no-parallel --no-daemon -x test build
      - name: 'Install GPG Secret Key'
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: 'Sign Jars'
        run: |
          export GPG_TTY=$(tty)
          /usr/lib/gnupg2/gpg-preset-passphrase -c ${{ secrets.GPG_KEYGRIP }} <<< ${{ secrets.GPG_PASSPHRASE }}
          for jar in build/libs/*.jar; do gpg --detach-sign --try-all-secrets --armor $jar; done
          for signed in build/libs/*.asc; do gpg --verify $signed; done
      - name: 'Upload to Draft Release'
        uses: ncipollo/release-action@v1
        with:
          draft: true
          name: "Test Signing"
          artifacts: build/libs/*
          token: ${{ secrets.GITHUB_TOKEN }}